### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by mcollina** [hmalphettes/redisdown#26]
Tests are currently failing badly on my machine:

```
# test simple del()
not ok 74 AbortError: EXEC can't be processed. The connection is already closed.
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { code: 'NR_CLOSED', command: 'EXEC', errors: [ { args: [ '_redisdown_test_db_:14:h', 'foo', 'bar' ], code: 'NR_CLOSED', command: 'HSET', position: 0 }, { args: [ '_redisdown_test_db_:14:z', 0, 'foo' ], code: 'NR_CLOSED', command: 'ZADD', position: 1 } ] }
    at: Multi.callback (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/del-test.js:88:9)
    stack: |-
      AbortError: EXEC can't be processed. The connection is already closed.
          at handle_offline_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:843:15)
          at RedisClient.internal_send_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:873:9)
          at Multi.exec_transaction (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/multi.js:115:18)
          at RedisDown.__exec (/Users/matteo/Repositories/redisdown/index.js:151:22)
          at RedisDown._put (/Users/matteo/Repositories/redisdown/index.js:113:7)
          at RedisDown.AbstractLevelDOWN.put (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract-leveldown.js:117:17)
          at Test.<anonymous> (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/del-test.js:87:8)
          at Test.bound [as _cb] (/Users/matteo/Repositories/redisdown/node_modules/tape/lib/test.js:63:32)
          at Test.run (/Users/matteo/Repositories/redisdown/node_modules/tape/lib/test.js:82:10)
          at Test.bound [as run] (/Users/matteo/Repositories/redisdown/node_modules/tape/lib/test.js:63:32)
  ...
not ok 75 AbortError: EXEC can't be processed. The connection is already closed.
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { code: 'NR_CLOSED', command: 'EXEC', errors: [ { args: [ '_redisdown_test_db_:14:h', 'foo' ], code: 'NR_CLOSED', command: 'HDEL', position: 0 }, { args: [ '_redisdown_test_db_:14:z', 'foo' ], code: 'NR_CLOSED', command: 'ZREM', position: 1 } ] }
    at: Multi.callback (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/del-test.js:90:11)
    stack: |-
      AbortError: EXEC can't be processed. The connection is already closed.
          at handle_offline_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:843:15)
          at RedisClient.internal_send_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:873:9)
          at Multi.exec_transaction (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/multi.js:115:18)
          at RedisDown.__exec (/Users/matteo/Repositories/redisdown/index.js:151:22)
          at RedisDown._del (/Users/matteo/Repositories/redisdown/index.js:117:7)
          at RedisDown.AbstractLevelDOWN.del (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract-leveldown.js:140:17)
          at Multi.callback (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/del-test.js:89:10)
          at multi_callback (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/multi.js:57:18)
          at /Users/matteo/Repositories/redisdown/node_modules/redis/lib/multi.js:116:9
          at callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
  ...
ok 76 entry propertly deleted
ok 77 value is undefined
not ok 78 NotFound error
  ---
    operator: ok
    expected: true
    actual:   false
    at: callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
  ...
# test del on non-existent key
not ok 79 AbortError: EXEC can't be processed. The connection is already closed.
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { code: 'NR_CLOSED', command: 'EXEC', errors: [ { args: [ '_redisdown_test_db_:14:h', 'blargh' ], code: 'NR_CLOSED', command: 'HDEL', position: 0 }, { args: [ '_redisdown_test_db_:14:z', 'blargh' ], code: 'NR_CLOSED', command: 'ZREM', position: 1 } ] }
    at: Multi.callback (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/del-test.js:103:9)
    stack: |-
      AbortError: EXEC can't be processed. The connection is already closed.
          at handle_offline_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:843:15)
          at RedisClient.internal_send_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:873:9)
          at Multi.exec_transaction (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/multi.js:115:18)
          at RedisDown.__exec (/Users/matteo/Repositories/redisdown/index.js:151:22)
          at RedisDown._del (/Users/matteo/Repositories/redisdown/index.js:117:7)
          at RedisDown.AbstractLevelDOWN.del (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract-leveldown.js:140:17)
          at Test.<anonymous> (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/del-test.js:102:8)
          at Test.bound [as _cb] (/Users/matteo/Repositories/redisdown/node_modules/tape/lib/test.js:63:32)
          at Test.run (/Users/matteo/Repositories/redisdown/node_modules/tape/lib/test.js:82:10)
          at Test.bound [as run] (/Users/matteo/Repositories/redisdown/node_modules/tape/lib/test.js:63:32)
  ...
# tearDown
ok 80 cleanup returned an error
# setUp common
ok 81 cleanup returned an error
# setUp db
# test argument-less get() throws
ok 82 no-arg get() throws
# test callback-less, 1-arg, get() throws
ok 83 callback-less, 1-arg get() throws
# test callback-less, 3-arg, get() throws
ok 84 callback-less, 2-arg get() throws
# test _serialize object
ok 85 should be equal
ok 86 undefined
# test _serialize buffer
ok 87 should be equivalent
ok 88 undefined
# test custom _serialize*
ok 89 should be equivalent
ok 90 undefined
# test simple get()
not ok 91 AbortError: EXEC can't be processed. The connection is already closed.
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { code: 'NR_CLOSED', command: 'EXEC', errors: [ { args: [ '_redisdown_test_db_:18:h', 'foo', 'bar' ], code: 'NR_CLOSED', command: 'HSET', position: 0 }, { args: [ '_redisdown_test_db_:18:z', 0, 'foo' ], code: 'NR_CLOSED', command: 'ZADD', position: 1 } ] }
    at: Multi.callback (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/get-test.js:88:9)
    stack: |-
      AbortError: EXEC can't be processed. The connection is already closed.
          at handle_offline_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:843:15)
          at RedisClient.internal_send_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:873:9)
          at Multi.exec_transaction (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/multi.js:115:18)
          at RedisDown.__exec (/Users/matteo/Repositories/redisdown/index.js:151:22)
          at RedisDown._put (/Users/matteo/Repositories/redisdown/index.js:113:7)
          at RedisDown.AbstractLevelDOWN.put (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract-leveldown.js:117:17)
          at Test.<anonymous> (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/get-test.js:87:8)
          at Test.bound [as _cb] (/Users/matteo/Repositories/redisdown/node_modules/tape/lib/test.js:63:32)
          at Test.run (/Users/matteo/Repositories/redisdown/node_modules/tape/lib/test.js:82:10)
          at Test.bound [as run] (/Users/matteo/Repositories/redisdown/node_modules/tape/lib/test.js:63:32)
  ...
not ok 92 AbortError: HGET can't be processed. The connection is already closed.
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { args: [ '_redisdown_test_db_:18:h', 'foo' ], code: 'NR_CLOSED', command: 'HGET' }
    at: callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
    stack: |-
      AbortError: HGET can't be processed. The connection is already closed.
          at handle_offline_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:843:15)
          at RedisClient.internal_send_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:873:9)
          at RedisClient.hget (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/commands.js:62:25)
          at RedisDown._get (/Users/matteo/Repositories/redisdown/index.js:97:10)
          at RedisDown.AbstractLevelDOWN.get (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract-leveldown.js:93:17)
          at Multi.callback (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/get-test.js:89:10)
          at multi_callback (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/multi.js:57:18)
          at /Users/matteo/Repositories/redisdown/node_modules/redis/lib/multi.js:116:9
          at callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
          at /Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:103:13
  ...
ok 93 should not be string by default
not ok 94 should be truthy
  ---
    operator: ok
    expected: true
    actual:   false
    at: callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
  ...
not ok 95 should not throw when converting value to a string
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'toString' of undefined]
    at: callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
    stack: |-
      TypeError: Cannot read property 'toString' of undefined
          at /Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/get-test.js:99:27
          at /Users/matteo/Repositories/redisdown/index.js:98:19
          at callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
          at /Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:103:13
          at nextTickCallbackWith0Args (node.js:420:9)
          at process._tickCallback (node.js:349:13)
  ...
not ok 96 should be equal
  ---
    operator: equal
    expected: 'bar'
    actual:   undefined
    at: callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
  ...
not ok 97 AbortError: HGET can't be processed. The connection is already closed.
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { args: [ '_redisdown_test_db_:18:h', 'foo' ], code: 'NR_CLOSED', command: 'HGET' }
    at: callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
    stack: |-
      AbortError: HGET can't be processed. The connection is already closed.
          at handle_offline_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:843:15)
          at RedisClient.internal_send_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:873:9)
          at RedisClient.hget (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/commands.js:62:25)
          at RedisDown._get (/Users/matteo/Repositories/redisdown/index.js:97:10)
          at RedisDown.AbstractLevelDOWN.get (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract-leveldown.js:93:17)
          at /Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/get-test.js:107:12
          at /Users/matteo/Repositories/redisdown/index.js:98:19
          at callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
          at /Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:103:13
          at nextTickCallbackWith0Args (node.js:420:9)
  ...
ok 98 should not be string by default
not ok 99 should be truthy
  ---
    operator: ok
    expected: true
    actual:   false
    at: callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
  ...
not ok 100 should not throw when converting value to a string
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'toString' of undefined]
    at: callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
    stack: |-
      TypeError: Cannot read property 'toString' of undefined
          at /Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/get-test.js:117:29
          at /Users/matteo/Repositories/redisdown/index.js:98:19
          at callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
          at /Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:103:13
          at nextTickCallbackWith0Args (node.js:420:9)
          at process._tickCallback (node.js:349:13)
  ...
not ok 101 should be equal
  ---
    operator: equal
    expected: 'bar'
    actual:   undefined
    at: callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
  ...
not ok 102 AbortError: HGET can't be processed. The connection is already closed.
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { args: [ '_redisdown_test_db_:18:h', 'foo' ], code: 'NR_CLOSED', command: 'HGET' }
    at: callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
    stack: |-
      AbortError: HGET can't be processed. The connection is already closed.
          at handle_offline_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:843:15)
          at RedisClient.internal_send_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:873:9)
          at RedisClient.hget (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/commands.js:62:25)
          at RedisDown._get (/Users/matteo/Repositories/redisdown/index.js:97:10)
          at RedisDown.AbstractLevelDOWN.get (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract-leveldown.js:93:17)
          at /Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/get-test.js:125:14
          at /Users/matteo/Repositories/redisdown/index.js:98:19
          at callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
          at /Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:103:13
          at nextTickCallbackWith0Args (node.js:420:9)
  ...
not ok 103 should be string if not buffer
  ---
    operator: ok
    expected: true
    actual:   false
    at: callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
  ...
not ok 104 should be equal
  ---
    operator: equal
    expected: 'bar'
    actual:   undefined
    at: callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
  ...
# test simultaniously get()
not ok 105 AbortError: EXEC can't be processed. The connection is already closed.
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { code: 'NR_CLOSED', command: 'EXEC', errors: [ { args: [ '_redisdown_test_db_:18:h', 'hello', 'world' ], code: 'NR_CLOSED', command: 'HSET', position: 0 }, { args: [ '_redisdown_test_db_:18:z', 0, 'hello' ], code: 'NR_CLOSED', command: 'ZADD', position: 1 } ] }
    at: Multi.callback (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/get-test.js:138:9)
    stack: |-
      AbortError: EXEC can't be processed. The connection is already closed.
          at handle_offline_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:843:15)
          at RedisClient.internal_send_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:873:9)
          at Multi.exec_transaction (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/multi.js:115:18)
          at RedisDown.__exec (/Users/matteo/Repositories/redisdown/index.js:151:22)
          at RedisDown._put (/Users/matteo/Repositories/redisdown/index.js:113:7)
          at RedisDown.AbstractLevelDOWN.put (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract-leveldown.js:117:17)
          at Test.<anonymous> (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/get-test.js:137:8)
          at Test.bound [as _cb] (/Users/matteo/Repositories/redisdown/node_modules/tape/lib/test.js:63:32)
          at Test.run (/Users/matteo/Repositories/redisdown/node_modules/tape/lib/test.js:82:10)
          at Test.bound [as run] (/Users/matteo/Repositories/redisdown/node_modules/tape/lib/test.js:63:32)
  ...
not ok 106 AbortError: HGET can't be processed. The connection is already closed.
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { args: [ '_redisdown_test_db_:18:h', 'hello' ], code: 'NR_CLOSED', command: 'HGET' }
    at: callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
    stack: |-
      AbortError: HGET can't be processed. The connection is already closed.
          at handle_offline_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:843:15)
          at RedisClient.internal_send_command (/Users/matteo/Repositories/redisdown/node_modules/redis/index.js:873:9)
          at RedisClient.hget (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/commands.js:62:25)
          at RedisDown._get (/Users/matteo/Repositories/redisdown/index.js:97:10)
          at RedisDown.AbstractLevelDOWN.get (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract-leveldown.js:93:17)
          at Multi.callback (/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/get-test.js:148:12)
          at multi_callback (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/multi.js:57:18)
          at /Users/matteo/Repositories/redisdown/node_modules/redis/lib/multi.js:116:9
          at callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
          at /Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:103:13
  ...
/Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/get-test.js:150
          t.equal(value.toString(), 'world')
                       ^

TypeError: Cannot read property 'toString' of undefined
    at /Users/matteo/Repositories/redisdown/node_modules/abstract-leveldown/abstract/get-test.js:150:24
    at /Users/matteo/Repositories/redisdown/index.js:98:19
    at callbackOrEmit (/Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:85:9)
    at /Users/matteo/Repositories/redisdown/node_modules/redis/lib/utils.js:103:13
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
npm ERR! Test failed.  See above for more details.
```

Redis: 3.2

I think the problem might be due to the `'*'` dependency on abstract leveldown. Maybe something has changed there that trigger problems here.
#25 might be related.

**Comment by atifsyedali** [comment]
I think maybe because of parallel tests connecting and closing the connection, and the driver using cached connection...https://github.com/hmalphettes/redisdown/blob/master/index.js#L29

**Comment by seigel** [comment]
I think the tests run cleanly now (excluding the pouchdb suite, which has some configuration challenges)
