### ISSUE TITLE
redisdown doesn't support level@8 architecture

### ISSUE THREAD

**Issue by darkpencil1** [hmalphettes/redisdown#43]
Hey, when copy pasting the current README example, we get this kind of an error.
 ```
  throw error
    ^
Error [InitializationError]: First argument must be an abstract-leveldown compliant store
    at new LevelUP (C:\folders\node_modules\levelup\lib\levelup.js:41:13)      
    at LevelUP (C:\folders\node_modules\levelup\lib\levelup.js:25:12)
    at Object.<anonymous> (C:\folders\foobar.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
```
According to this thread [https://github.com/fergiemcdowall/search-index/issues/591](https://github.com/fergiemcdowall/search-index/issues/591)

> "The whole levelup/leveldown ecosystem has undergone a upgrade recently, with the unfortunate consequence that many of the old *downs are no longer usable."

**Any plans to upgrade to level@8 architecture?**

**Comment by seigel** [comment]
Wow.  You are right, things have changed quite a lot!  How familiar are you with the new architecture?  Any chance you know a way to make it work with level@8?

**Comment by darkpencil1** [comment]
Thanks for the quick response! I've no prior experience with level, so I can't take this up myself.
